include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - always_declare_return_types
    - annotate_overrides
    - avoid_empty_else
    - avoid_print
    - avoid_unnecessary_containers
    - avoid_web_libraries_in_flutter
    - cancel_subscriptions
    - close_sinks
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_final_fields
    - prefer_final_locals
    - prefer_single_quotes
    - sort_child_properties_last
    - unnecessary_brace_in_string_interps
    - use_key_in_widget_constructors

analyzer:
  errors:
    missing_return: error
    dead_code: warning
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'
